CREATE SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_PRODUCT;
CREATE SEQUENCE SEQ_ORDER;

CREATE TABLE TBL_MEMBER(
	MEMBER_NUMBER NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(1000),
	MEMBER_PW VARCHAR2(1000),
	MEMBER_NAME VARCHAR2(1000)
);

SELECT * FROM TBL_MEMBER;

INSERT INTO TBL_MEMBER
(MEMBER_NUMBER, MEMBER_ID, MEMBER_PW, MEMBER_NAME)
VALUES(SEQ_MEMBER.NEXTVAL, 'kim1234', '1234', '김윤규');

INSERT INTO TBL_MEMBER
(MEMBER_NUMBER, MEMBER_ID, MEMBER_PW, MEMBER_NAME)
VALUES(SEQ_MEMBER.NEXTVAL, 'kim5678', '5678', '김길동');

CREATE TABLE TBL_PRODUCT(
	PRODUCT_NUMBER NUMBER PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(1000),
	PRODUCT_PRICE NUMBER,
	PRODUCT_STOCK NUMBER
);

SELECT * FROM TBL_PRODUCT;

INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK)
VALUES(SEQ_PRODUCT.NEXTVAL, '포카칩', 1500, 64);

INSERT INTO TBL_PRODUCT
(PRODUCT_NUMBER, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK)
VALUES(SEQ_PRODUCT.NEXTVAL, '군만두', 5500, 128);

CREATE TABLE TBL_ORDER(
	ORDER_NUMBER NUMBER PRIMARY KEY,
	PRODUCT_COUNT NUMBER,
	ORDER_TOTAL_PRICE NUMBER,
	PRODUCT_NUMBER NUMBER,
	MEMBER_NUMBER NUMBER
);

ALTER TABLE TBL_ORDER ADD CONSTRAINT FK_ORDER_PRODUCT_NUMBER
FOREIGN KEY(PRODUCT_NUMBER) REFERENCES TBL_PRODUCT(PRODUCT_NUMBER)
ON DELETE CASCADE;

ALTER TABLE TBL_ORDER ADD CONSTRAINT FK_ORDER_MEMBER_NUMBER
FOREIGN KEY(MEMBER_NUMBER) REFERENCES TBL_MEMBER(MEMBER_NUMBER)
ON DELETE CASCADE;

SELECT * FROM TBL_ORDER;

INSERT INTO TBL_ORDER
(ORDER_NUMBER, PRODUCT_COUNT, ORDER_TOTAL_PRICE, PRODUCT_NUMBER, MEMBER_NUMBER)
VALUES(SEQ_ORDER.NEXTVAL, 3, (SELECT PRODUCT_PRICE * 3 FROM TBL_PRODUCT WHERE PRODUCT_NUMBER = 2), 2, 2);

/*주문번호가 1번인 상품을 구매한 회원의 이름 조회*/

SELECT M.MEMBER_NAME FROM 
TBL_ORDER O JOIN TBL_MEMBER M
ON O.MEMBER_NUMBER = M.MEMBER_NUMBER AND ORDER_NUMBER =1;

/*주문 시 소진 된 재고를 조회하여 그 만큼을 기존 재고에서 차감한다.*/

UPDATE TBL_PRODUCT  
SET PRODUCT_STOCK = PRODUCT_STOCK - (SELECT PRODUCT_COUNT FROM TBL_ORDER WHERE ORDER_NUMBER = 1)
WHERE PRODUCT_NUMBER = (SELECT PRODUCT_NUMBER FROM TBL_ORDER WHERE ORDER_NUMBER = 1);